# This is the default configuration file for Polygon2DOMjudge
# If you want to override the default configuration,
# create a new file named "config.toml" and override the default values there

language_preference = ["english", "russian", "chinese"]

[flag]
"fcmp.cpp" = "case_sensitive space_change_sensitive"
"lcmp.cpp" = "case_sensitive"
"rcmp4.cpp" = "float_tolerance 1e-4"
"rcmp6.cpp" = "float_tolerance 1e-6"
"rcmp9.cpp" = "float_tolerance 1e-9"
"wcmp.cpp" = "case_sensitive"
# "hcmp.cpp" = ""
# "ncmp.cpp" = ""
# "nyesno.cpp" = ""
# "yesno.cpp" = ""

[tag]
main = ["accepted"]
accepted = ["accepted"]
wrong-answer = ["wrong_answer"]
presentation-error = ["wrong_answer"]
time-limit-exceeded = ["time_limit_exceeded"]
time-limit-exceeded-or-accepted = ["time_limit_exceeded", "accepted"]
time-limit-exceeded-or-memory-limit-exceeded = [
    "time_limit_exceeded",
    "run_time_error",
]
memory-limit-exceeded = ["run_time_error"]
rejected = ["wrong_answer", "time_limit_exceeded", "run_time_error"]
failed = ["wrong_answer", "time_limit_exceeded", "run_time_error"]

[example_path_pattern]
input = "example.%02d"
output = "example.%02d.a"

[comment_str]
c = "//"
cpp = "//"
java = "//"
python = "#"
kotlin = "//"
